{% set name = "fooof" %}
{% set version = "1.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 6b38f28a8a9a787121d4741335ca4737c65d356dfbf64d9e5c04cd5510a5a72c

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - numpy
    - pip
    - python >=3.5
    - scipy >=0.19.0
  run:
    - numpy
    - python >=3.5
    - scipy >=0.19.0

test:
  imports:
    - fooof
    - fooof.analysis
    - fooof.bands
    - fooof.core
    - fooof.data
    - fooof.objs
    - fooof.plts
    - fooof.sim
    - fooof.tests
    - fooof.tests.analysis
    - fooof.tests.bands
    - fooof.tests.core
    - fooof.tests.data
    - fooof.tests.objs
    - fooof.tests.plts
    - fooof.tests.sim
    - fooof.tests.utils
    - fooof.utils
  requires:
    - pytest

about:
  home: "https://github.com/fooof-tools/fooof"
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "fitting oscillations & one-over f"
  doc_url: https://fooof-tools.github.io/fooof/
  dev_url: "https://github.com/fooof-tools/fooof"

extra:
  recipe-maintainers:
    - ryanhammonds
