{% set name = "fooof" %}
{% set version = "1.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 58d415a383470d7f23fa1823cd5ef6c6545e05eef4ead9bd96db3436fb8f4092

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - numpy
    - pip
    - python {{ python_min }}
    - scipy >=0.19.0
  run:
    - numpy
    - python >={{ python_min }}
    - scipy >=0.19.0

test:
  imports:
    - fooof
    - fooof.analysis
    - fooof.bands
    - fooof.core
    - fooof.data
    - fooof.objs
    - fooof.plts
    - fooof.sim
    - fooof.tests
    - fooof.tests.analysis
    - fooof.tests.bands
    - fooof.tests.core
    - fooof.tests.data
    - fooof.tests.objs
    - fooof.tests.plts
    - fooof.tests.sim
    - fooof.tests.utils
    - fooof.utils
  requires:
    - pytest
    - python {{ python_min }}

about:
  home: "https://github.com/fooof-tools/fooof"
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "fitting oscillations & one-over f"
  doc_url: https://fooof-tools.github.io/fooof/
  dev_url: "https://github.com/fooof-tools/fooof"

extra:
  recipe-maintainers:
    - TomDonoghue
    - ryanhammonds
